name: Deploy React Vite App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js using nvm (Node Version Manager)
      - name: Set up Node.js 20
        run: |
          # Install nvm (Node Version Manager)
          curl -fsSL https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash
          # Source nvm to use it in the current shell
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
          [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
          # Install Node.js 20 and set it as the default version
          nvm install 20
          nvm use 20

      # Step 3: Set up SSH agent and add private key
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Step 4: Deploy to the server
      - name: Deploy to server
        run: |
          # Step 4.1: SSH into the server and deploy
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
            # Ensure nvm is available on the server
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
            [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

            # Step 4.2: Navigate to the app directory
            cd ~/projects/ichasanidis-wholesale

            # Step 4.3: Pull the latest changes
            git reset --hard origin/main

            # Step 4.4: Clear npm cache and reinstall dependencies
            rm -rf node_modules package-lock.json  # Remove existing dependencies
            npm cache clean --force                # Clear npm cache
            npm install                             # Install fresh dependencies

            # Step 4.5: Build the React Vite app
            npm run build

            # Step 4.6: Build and replace the Docker image
            docker build -t ichasanidis.com:latest .

            # Step 4.7: Stop and remove the old container
            docker rm -f ichasanidis.com || true  # Ignore errors if the container doesn't exist

            # Step 4.8: Run the new Docker container
            docker run -d --name ichasanidis.com --network nginx-proxy-manager_default -p 5173:5173 ichasanidis.com
          EOF
