name: Deploy React Vite App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up SSH agent and add private key
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Step 3: Deploy to the server
      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
            # Step 3.1: Navigate to the app directory
            cd ~/projects/ichasanidis-wholesale

            # Step 3.2: Pull the latest changes
            git reset --hard origin/main

            # Step 3.3: Build the React Vite app
            npm ci  # Install dependencies
            npm run build  # Build the app

            # Step 3.4: Build and replace the Docker image
            docker build -t ichasanidis.com:latest .

            # Step 3.5: Stop and remove the old container
            docker rm -f ichasanidis.com || true  # Ignore errors if the container doesn't exist

            # Step 3.6: Run the new Docker container
            docker run -d --name ichasanidis.com --network nginx-proxy-manager_default -p 5173:5173 ichasanidis.com
          EOF
