name: Deploy React Vite App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up SSH agent and add private key
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Step 3: Deploy to the server
      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
            cd ~/projects/ichasanidis-wholesale

            # Pull latest changes
            git pull

            # Build and restart the Docker container
            docker build -t ioannischasanidisjewelry-frontend:latest .
            docker rm -f ioannischasanidisjewelry-frontend || true
            docker run -d --name ioannischasanidisjewelry-frontend -p 5173:5173 ioannischasanidisjewelry-frontend
          EOF
