name: Deploy React Vite App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install Node.js 20 using nvm
      - name: Set up Node.js 20
        run: |
          # Install nvm (Node Version Manager)
          curl -fsSL https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash
          # Source nvm so we can use it in this step
          source ~/.bashrc
          nvm install 20  # Install Node.js version 20
          nvm use 20      # Use Node.js version 20

      # Step 3: Set up SSH agent and add private key
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Step 4: Deploy to the server
      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
            # Step 4.1: Navigate to the app directory
            cd ~/projects/ichasanidis-wholesale

            # Step 4.2: Pull the latest changes
            git reset --hard origin/main

            # Step 4.3: Clear npm cache and reinstall dependencies
            rm -rf node_modules package-lock.json  # Remove existing dependencies
            npm cache clean --force                # Clear npm cache
            npm install                             # Install fresh dependencies

            # Step 4.4: Build the React Vite app
            npm run build

            # Step 4.5: Build and replace the Docker image
            docker build -t ichasanidis.com:latest .

            # Step 4.6: Stop and remove the old container
            docker rm -f ichasanidis.com || true  # Ignore errors if the container doesn't exist

            # Step 4.7: Run the new Docker container
            docker run -d --name ichasanidis.com --network nginx-proxy-manager_default -p 5173:5173 ichasanidis.com
          EOF
