name: Deploy React Vite App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js (for local build steps, if needed)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Step 3: Set up SSH agent and add private key
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Step 4: Deploy to the server
      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
            cd ~/projects/ichasanidis-wholesale

            # Pull latest changes
            git reset --hard origin/main

            # Build and restart the Docker container
            docker build -t ichasanidis.com:latest .
            docker rm -f ichasanidis.com || true
            docker run -d --name ichasanidis.com --network nginx-proxy-manager_default -p 5173:5173 ichasanidis.com
          EOF
